name: Integration Test Github
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      if: ${{ github.actor != 'dependabot[bot]' }}
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: docker.pkg.github.com/elgohr/publish-docker-github-action/publish-docker-github-action
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
